version: '3'
services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
  php:
    container_name: php-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '9000:9000'
    depends_on:
      - mysql
    volumes:
      - ./:/app
    links:
      - mysql
  mysql:
    container_name: mysql_server
    build:
      context: ./library/Mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: analytics
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123456
#      DB_HOST: localhost
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
  redis:
    container_name: redis
    build:
      context: ./library/Redis
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  esdata:
    driver: local